name: Build Ubuntu 20.04 executable

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build executable
        run: |
          docker build -t allure-revision -f docker/ubuntu20.04/Dockerfile .
          docker run allure-revision
          docker cp $(docker ps -lq):/dist/allure_revision_ubuntu20.04 .

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allure_revision_ubuntu20.04
          path: |
            allure_revision_ubuntu20.04 
