name: Build Windows executable

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable
        run: |
          pyinstaller --onefile main/make.py --name allure_revision_win

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allure_revision_win
          path: |
            dist/allure_revision_win.exe